backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - label: Pages
    name: pages
    files:
      - label: About
        name: about
        file: src/content/about.md
        fields:
          - { name: title, label: Title }
          - { name: body, label: Body, widget: markdown }
  - label: Writing
    name: writing
    files:
      - label: References
        name: references
        file: src/content/writing/references.md
        fields:
          - { name: title, label: Title }
          - { name: date, label: Date, widget: datetime }
          - { name: body, label: Body, widget: markdown }
  - label: Stories
    name: stories
    folder: src/content/writing/stories
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
  - label: Projects
    name: projects
    folder: src/content/projects
    create: true
    extension: yml
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description, widget: text }
      - { name: linkTo, label: Link To Project, widget: string }
      - { name: technologiesUsed, label: Technologies Used, widget: list }