backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - name: writing
    label: Writing
    folder: src/content
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    extension: yml
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description, widget: text }
      - { name: linkTo, label: Link To Project, widget: string }
      - { name: technologiesUsed, label: Technologies Used, widget: list }